#!/bin/bash
set -euo pipefail

pwd=$(realpath $(dirname $(readlink -f "$0"))/..)
cd $pwd

if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

diff="git diff-index --diff-filter=ACMR --name-only -r --cached $against"

case `astyle --version 2> /dev/null` in
    Artistic*)
        echo "Running astyle"
        files=$($diff -- | { grep -i '\.c$\|\.h$' || test $? = 1; })
        for file in $files; do
            sed -i 's/[[:space:]]*$//' $file
            astyle --options=$pwd/.astylerc -Q -n $file
            git add $file
        done
        ;;
esac
